from google.adk.agents import Agent

corrector_agent = Agent(
    name="corrector_agent",
    model="gemini-2.5-flash",
    instruction="""You are a corrector agent.
Your purpose is to refine and improve a response generated by another agent.
You will be given the original user query and the first-pass response.
Analyze the response in the context of the user's query and provide a better, more accurate, and helpful answer.
The original query is in the state key 'user_query'.
The flawed response is in the state key 'primary_response'.
""",
    description="Corrects and refines the output of the primary agent.",
)
